### ISSUE TITLE
Some text strings missing in the app

### ISSUE THREAD

**Issue by liskin** [nhsx/covid-19-app-android-ag-public#33] opened 2020-10-21 23:07 UTC
**Describe the bug**
Symptoms checkboxes are empty in the app, and the local covid alert level screen also misses all text.

**To Reproduce**
1. Go to 'Select symptoms' or 'Local Covid Alert Level'

**Expected behavior**
Some or all text is missing, as demonstrated by the attached screenshots:

**Screenshots**
![Screenshot_20201018-165049_NHS Covid-19](https://user-images.githubusercontent.com/300342/96799055-93608b00-1402-11eb-87c2-a95fee137557.png)
![Screenshot_20201018-165056_NHS Covid-19](https://user-images.githubusercontent.com/300342/96799063-99ef0280-1402-11eb-98ed-e19a4ba22c32.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e, Sony Xperia X Compact
 - OS: Android 10, Android 8
 - Version: 3.7.2 (85)
 - Locale: cs_CZ (I'm guessing this may be relevant)

**Comment by clentfort** [comment] 2020-10-28 00:06
Same for German users

**Comment by mikedlr** [comment] 2020-10-28 12:25
@clentfort  - [newspaper article on the subject](https://www.theguardian.com/world/2020/oct/28/nhs-covid-app-does-not-work-for-phones-set-to-french-and-spanish) - apparently this applies to at least French and Spanish as well.

**Comment by analca3** [comment] 2020-10-28 15:55
I can confirm this happens in my Poco F2 Pro, Android 10, set in Spanish. The first version of the app worked perfectly but after the first update it doesn't show the strings.

**Comment by liskin** [comment] 2020-10-29 13:33
This seems to have been fixed by the latest update.

It's quite disappointing thought that this repo isn't updated with the code that was deployed to Google Play. Almost as if the authors of the NHS app didn't understand how open-source works. :-(

**Comment by analca3** [comment] 2020-10-29 14:45
Yes, it's fixed for me now. Hope they update the repo soon.

**Comment by skenaja** [comment] 2020-10-29 18:25
Repo seems to have been updated. Looks like it was fixed in [36ba4bd](https://github.com/nhsx/covid-19-app-android-ag-public/commit/36ba4bd0ab9dad2b869310f2b038791f462df397#diff-f83f8e38a0516fad999b0ab92f40bb99622161a96e8ffacf6646dc5ea6a9a0d9) with a fallback to `en` for untranslated strings. 

Shame they're not doing nice commit messages in this repo in line with the [GDS guidelines](https://www.gov.uk/service-manual/technology/maintaining-version-control-in-coding#writing-commit-messages).

**Comment by nhs-covid19** [comment] 2020-11-09 11:51
Thanks for your interest in the NHS Covid-19 project, and for reporting this issue. This was the result of incorrect fallback behaviour for untranslated strings, as @skenaja points out, and has now been fixed. With regard to commit comments, as has been discussed already in some of the other public repos for this app, this isn't the primary repository, so individual commit messages are not available. 
With regard to timely updates of the open source version,  @liskin , we do endeavour to update the open source repos with the correct code corresponding to a release very quickly after a new version of the app is released - usually within a few minutes. This time it did take a bit longer, as there were quite a few new repositories, including all the code for our risk scoring algorithms. e.g. https://github.com/nhsx/riskscore-kt-public (and the corresponding Swift repos for iOS)

**Closed by nhs-covid19** 2020-11-09 11:51 UTC
Labels: bug

**Comment by liskin** [comment] 2020-11-09 11:55
> this isn't the primary repository, so individual commit messages are not available

Can you point us to the primary repository then?
